---
apiVersion: v1
kind: Namespace
metadata:
  name: phase-4
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: legacy-app
    alert: "true"
  name: legacy-app
  namespace: phase-4
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1; exit 1
    image: busybox
    name: legacy-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
