---
apiVersion: v1
kind: Namespace
metadata:
  name: phase-4
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: crashloop-demo
  name: crashloop-demo
  namespace: phase-4
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10; exit 1
    image: busybox
    name: crashloop-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
